"use client"
// import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "react-redux";
import Header from "@/components/layout/Header/header";
import { store } from "@/stores";
import Footer from "@/components/layout/Footer";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
// 
// export const metadata: Metadata = {
//   title: "Portfolio",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Provider store={store}>
          <Header />
          <main className="">
            {children}
          </main>
          <div className="">
            <Footer/>
          </div>
        </Provider>
      </body>
    </html>
  );
}
